# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('due_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('importance', models.IntegerField(max_length=1)),
                ('urgency', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.User'),
        ),
    ]
